services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 1m30s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_DB=restapi_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sassassa12
    ports:
      - "5432:5432"
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"