services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=restapi_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sassassa12
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d restapi_dev -U postgres -w"]
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    build: .
    depends_on:
      db:
        condition: service_completed_successfully
    ports:
      - "8081:8081"